### ISSUE TITLE
djs dil desteği

### ISSUE THREAD

**Issue by lunexdev** [falsisdev/kremlin#1]
BOT KESİNLİKLE DJS DİLİNE ÇEVRİLMELİ

**Comment by falsisdev** [comment]
Basit olsaydı yapardım. N-ne bir dakika djs dili ne amk

**Comment by falsisdev** [comment]
çok komut var

**Comment by lunexdev** [comment]
olabilir js dili çok kötü

**Comment by lunexdev** [comment]
djs diline çevir botu

**Comment by falsisdev** [comment]
ciddi ol az enayi

**Comment by berat141** [comment]
Bdfd diline çevirin lnaaaa

**Comment by falsisdev** [comment]
kutsal lenguiç
